version: "3.7"
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - transaction_dbdata:/var/lib/postgresql/data/

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    ports:
      - 9092:9092
  
  antifraud-service:
    build:
      dockerfile: Dockerfile
      context: ./antifraud-service
    depends_on:
      - kafka
    command: pnpm run start:prod
    environment:
      KAFKA_LISTENER: 'kafka:29092'

  transaction-api:
    build:
      dockerfile: Dockerfile
      context: ./transaction-api
    depends_on:
      - kafka
      - postgres
    command: >
      sh -c "pnpm prisma migrate deploy && pnpm start:prod"
    ports:
      - 3001:3001
    environment:
      KAFKA_LISTENER: 'kafka:29092'
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432'

volumes:
  transaction_dbdata:
